# Instruction pour prendre une image de base
FROM nginx

# Instruction pour copier un fichier d'un emplacement machine vers un emplacement conteneur
COPY ./index.html /usr/share/nginx/html/index.html
# ADD ./index.html /usr/share/nginx/html/index.html

# Pour informer d'un port qui peut être utiliser dans le cadre d'un port forwarding
EXPOSE 80